	.section .rodata

	.align 2
DirectSoundWaveData_clover_00257c50::
	.incbin "sound/direct_sound_samples/clover/clover_00257c50.bin"
	.align 2
DirectSoundWaveData_clover_002d8e9c::
	.incbin "sound/direct_sound_samples/clover/clover_002d8e9c.bin"
	.align 2
DirectSoundWaveData_clover_003bb470::
	.incbin "sound/direct_sound_samples/clover/clover_003bb470.bin"
	.align 2
DirectSoundWaveData_clover_003bb560::
	.incbin "sound/direct_sound_samples/clover/clover_003bb560.bin"
	.align 2
DirectSoundWaveData_clover_003bb700::
	.incbin "sound/direct_sound_samples/clover/clover_003bb700.bin"
	.align 2
DirectSoundWaveData_clover_004a8354::
	.incbin "sound/direct_sound_samples/clover/clover_004a8354.bin"
	.align 2
DirectSoundWaveData_clover_004a9f3c::
	.incbin "sound/direct_sound_samples/clover/clover_004a9f3c.bin"
	.align 2
DirectSoundWaveData_clover_004ab280::
	.incbin "sound/direct_sound_samples/clover/clover_004ab280.bin"
	.align 2
DirectSoundWaveData_clover_004ad038::
	.incbin "sound/direct_sound_samples/clover/clover_004ad038.bin"
	.align 2
DirectSoundWaveData_clover_004b0b0c::
	.incbin "sound/direct_sound_samples/clover/clover_004b0b0c.bin"
	.align 2
DirectSoundWaveData_clover_004b23e8::
	.incbin "sound/direct_sound_samples/clover/clover_004b23e8.bin"
	.align 2
DirectSoundWaveData_clover_004b5450::
	.incbin "sound/direct_sound_samples/clover/clover_004b5450.bin"
	.align 2
DirectSoundWaveData_clover_004b9c70::
	.incbin "sound/direct_sound_samples/clover/clover_004b9c70.bin"
	.align 2
DirectSoundWaveData_clover_004bc8b8::
	.incbin "sound/direct_sound_samples/clover/clover_004bc8b8.bin"
	.align 2
DirectSoundWaveData_clover_004c40e8::
	.incbin "sound/direct_sound_samples/clover/clover_004c40e8.bin"
	.align 2
DirectSoundWaveData_clover_004c4aa0::
	.incbin "sound/direct_sound_samples/clover/clover_004c4aa0.bin"
	.align 2
DirectSoundWaveData_clover_004c5920::
	.incbin "sound/direct_sound_samples/clover/clover_004c5920.bin"
	.align 2
DirectSoundWaveData_clover_004c6794::
	.incbin "sound/direct_sound_samples/clover/clover_004c6794.bin"
	.align 2
DirectSoundWaveData_clover_004c7fa8::
	.incbin "sound/direct_sound_samples/clover/clover_004c7fa8.bin"
	.align 2
DirectSoundWaveData_clover_004c954c::
	.incbin "sound/direct_sound_samples/clover/clover_004c954c.bin"
	.align 2
DirectSoundWaveData_clover_004cab30::
	.incbin "sound/direct_sound_samples/clover/clover_004cab30.bin"
	.align 2
DirectSoundWaveData_clover_004d9258::
	.incbin "sound/direct_sound_samples/clover/clover_004d9258.bin"
	.align 2
DirectSoundWaveData_clover_004dced8::
	.incbin "sound/direct_sound_samples/clover/clover_004dced8.bin"
	.align 2
DirectSoundWaveData_clover_004ddf74::
	.incbin "sound/direct_sound_samples/clover/clover_004ddf74.bin"
	.align 2
DirectSoundWaveData_clover_004ee778::
	.incbin "sound/direct_sound_samples/clover/clover_004ee778.bin"
	.align 2
DirectSoundWaveData_clover_004f038c::
	.incbin "sound/direct_sound_samples/clover/clover_004f038c.bin"
	.align 2
DirectSoundWaveData_clover_004fc470::
	.incbin "sound/direct_sound_samples/clover/clover_004fc470.bin"
	.align 2
DirectSoundWaveData_clover_004fe57c::
	.incbin "sound/direct_sound_samples/clover/clover_004fe57c.bin"
	.align 2
DirectSoundWaveData_clover_00506c68::
	.incbin "sound/direct_sound_samples/clover/clover_00506c68.bin"
	.align 2
DirectSoundWaveData_clover_0050d7b4::
	.incbin "sound/direct_sound_samples/clover/clover_0050d7b4.bin"
	.align 2
DirectSoundWaveData_clover_0050eb84::
	.incbin "sound/direct_sound_samples/clover/clover_0050eb84.bin"
	.align 2
DirectSoundWaveData_clover_00510c4c::
	.incbin "sound/direct_sound_samples/clover/clover_00510c4c.bin"
	.align 2
DirectSoundWaveData_clover_0053ba58::
	.incbin "sound/direct_sound_samples/clover/clover_0053ba58.bin"
	.align 2
DirectSoundWaveData_clover_00562320::
	.incbin "sound/direct_sound_samples/clover/clover_00562320.bin"
	.align 2
DirectSoundWaveData_clover_005632d8::
	.incbin "sound/direct_sound_samples/clover/clover_005632d8.bin"
	.align 2
DirectSoundWaveData_clover_005643ac::
	.incbin "sound/direct_sound_samples/clover/clover_005643ac.bin"
	.align 2
DirectSoundWaveData_clover_00613f90::
	.incbin "sound/direct_sound_samples/clover/clover_00613f90.bin"
	.align 2
DirectSoundWaveData_clover_006a3bd0::
	.incbin "sound/direct_sound_samples/clover/clover_006a3bd0.bin"
	.align 2
DirectSoundWaveData_clover_006a6458::
	.incbin "sound/direct_sound_samples/clover/clover_006a6458.bin"
	.align 2
DirectSoundWaveData_clover_006b2198::
	.incbin "sound/direct_sound_samples/clover/clover_006b2198.bin"
	.align 2
DirectSoundWaveData_clover_00803548::
	.incbin "sound/direct_sound_samples/clover/clover_00803548.bin"
	.align 2
DirectSoundWaveData_clover_00804b8c::
	.incbin "sound/direct_sound_samples/clover/clover_00804b8c.bin"
	.align 2
DirectSoundWaveData_clover_0080c93c::
	.incbin "sound/direct_sound_samples/clover/clover_0080c93c.bin"
	.align 2
DirectSoundWaveData_clover_0080eb74::
	.incbin "sound/direct_sound_samples/clover/clover_0080eb74.bin"
	.align 2
DirectSoundWaveData_clover_00812050::
	.incbin "sound/direct_sound_samples/clover/clover_00812050.bin"
	.align 2
DirectSoundWaveData_clover_00814fac::
	.incbin "sound/direct_sound_samples/clover/clover_00814fac.bin"
	.align 2
DirectSoundWaveData_clover_0081c6e8::
	.incbin "sound/direct_sound_samples/clover/clover_0081c6e8.bin"
	.align 2
DirectSoundWaveData_clover_0081da08::
	.incbin "sound/direct_sound_samples/clover/clover_0081da08.bin"
	.align 2
DirectSoundWaveData_clover_008206ec::
	.incbin "sound/direct_sound_samples/clover/clover_008206ec.bin"
	.align 2
DirectSoundWaveData_clover_008210a4::
	.incbin "sound/direct_sound_samples/clover/clover_008210a4.bin"
	.align 2
DirectSoundWaveData_clover_00823578::
	.incbin "sound/direct_sound_samples/clover/clover_00823578.bin"
	.align 2
DirectSoundWaveData_clover_0082640c::
	.incbin "sound/direct_sound_samples/clover/clover_0082640c.bin"
	.align 2
DirectSoundWaveData_clover_00828a90::
	.incbin "sound/direct_sound_samples/clover/clover_00828a90.bin"
	.align 2
DirectSoundWaveData_clover_0082ae94::
	.incbin "sound/direct_sound_samples/clover/clover_0082ae94.bin"
	.align 2
DirectSoundWaveData_clover_0082dbec::
	.incbin "sound/direct_sound_samples/clover/clover_0082dbec.bin"
	.align 2
DirectSoundWaveData_clover_00830064::
	.incbin "sound/direct_sound_samples/clover/clover_00830064.bin"
	.align 2
DirectSoundWaveData_clover_00831570::
	.incbin "sound/direct_sound_samples/clover/clover_00831570.bin"
	.align 2
DirectSoundWaveData_clover_00833294::
	.incbin "sound/direct_sound_samples/clover/clover_00833294.bin"
	.align 2
DirectSoundWaveData_clover_008340c4::
	.incbin "sound/direct_sound_samples/clover/clover_008340c4.bin"
	.align 2
DirectSoundWaveData_clover_0083a3d4::
	.incbin "sound/direct_sound_samples/clover/clover_0083a3d4.bin"
	.align 2
DirectSoundWaveData_clover_0083b358::
	.incbin "sound/direct_sound_samples/clover/clover_0083b358.bin"
	.align 2
DirectSoundWaveData_clover_0083d9dc::
	.incbin "sound/direct_sound_samples/clover/clover_0083d9dc.bin"
	.align 2
DirectSoundWaveData_clover_00941950::
	.incbin "sound/direct_sound_samples/clover/clover_00941950.bin"
	.align 2
DirectSoundWaveData_clover_00942c30::
	.incbin "sound/direct_sound_samples/clover/clover_00942c30.bin"
	.align 2
DirectSoundWaveData_clover_00943dc4::
	.incbin "sound/direct_sound_samples/clover/clover_00943dc4.bin"
	.align 2
DirectSoundWaveData_clover_00945114::
	.incbin "sound/direct_sound_samples/clover/clover_00945114.bin"
	.align 2
DirectSoundWaveData_clover_009465f4::
	.incbin "sound/direct_sound_samples/clover/clover_009465f4.bin"
	.align 2
DirectSoundWaveData_clover_00957a5c::
	.incbin "sound/direct_sound_samples/clover/clover_00957a5c.bin"
	.align 2
DirectSoundWaveData_clover_0096fc74::
	.incbin "sound/direct_sound_samples/clover/clover_0096fc74.bin"
	.align 2
DirectSoundWaveData_clover_009c7510::
	.incbin "sound/direct_sound_samples/clover/clover_009c7510.bin"
	.align 2
DirectSoundWaveData_clover_00a121a4::
	.incbin "sound/direct_sound_samples/clover/clover_00a121a4.bin"
	.align 2
DirectSoundWaveData_clover_00a17438::
	.incbin "sound/direct_sound_samples/clover/clover_00a17438.bin"
	.align 2
DirectSoundWaveData_clover_00a19f44::
	.incbin "sound/direct_sound_samples/clover/clover_00a19f44.bin"
	.align 2
DirectSoundWaveData_clover_00a1cfd0::
	.incbin "sound/direct_sound_samples/clover/clover_00a1cfd0.bin"
	.align 2
DirectSoundWaveData_clover_00a1e2d8::
	.incbin "sound/direct_sound_samples/clover/clover_00a1e2d8.bin"
	.align 2
DirectSoundWaveData_clover_00a21c0c::
	.incbin "sound/direct_sound_samples/clover/clover_00a21c0c.bin"
	.align 2
DirectSoundWaveData_clover_00a24750::
	.incbin "sound/direct_sound_samples/clover/clover_00a24750.bin"
	.align 2
DirectSoundWaveData_clover_00a28f48::
	.incbin "sound/direct_sound_samples/clover/clover_00a28f48.bin"
	.align 2
DirectSoundWaveData_clover_00a2c378::
	.incbin "sound/direct_sound_samples/clover/clover_00a2c378.bin"
	.align 2
DirectSoundWaveData_clover_00a2eafc::
	.incbin "sound/direct_sound_samples/clover/clover_00a2eafc.bin"
	.align 2
DirectSoundWaveData_clover_00a373cc::
	.incbin "sound/direct_sound_samples/clover/clover_00a373cc.bin"
	.align 2
DirectSoundWaveData_clover_00a3b858::
	.incbin "sound/direct_sound_samples/clover/clover_00a3b858.bin"
	.align 2
DirectSoundWaveData_clover_00a3f5c8::
	.incbin "sound/direct_sound_samples/clover/clover_00a3f5c8.bin"
	.align 2
DirectSoundWaveData_clover_00a42d94::
	.incbin "sound/direct_sound_samples/clover/clover_00a42d94.bin"
	.align 2
DirectSoundWaveData_clover_00a45fe4::
	.incbin "sound/direct_sound_samples/clover/clover_00a45fe4.bin"
	.align 2
DirectSoundWaveData_clover_00a49a08::
	.incbin "sound/direct_sound_samples/clover/clover_00a49a08.bin"
	.align 2
DirectSoundWaveData_clover_00a4d7b0::
	.incbin "sound/direct_sound_samples/clover/clover_00a4d7b0.bin"
	.align 2
DirectSoundWaveData_clover_00a8a314::
	.incbin "sound/direct_sound_samples/clover/clover_00a8a314.bin"
	.align 2
DirectSoundWaveData_clover_00ade494::
	.incbin "sound/direct_sound_samples/clover/clover_00ade494.bin"
	.align 2
DirectSoundWaveData_clover_00adf438::
	.incbin "sound/direct_sound_samples/clover/clover_00adf438.bin"
	.align 2
DirectSoundWaveData_clover_00ae0544::
	.incbin "sound/direct_sound_samples/clover/clover_00ae0544.bin"
	.align 2
DirectSoundWaveData_clover_00ae14c0::
	.incbin "sound/direct_sound_samples/clover/clover_00ae14c0.bin"
	.align 2
DirectSoundWaveData_clover_00ae2b88::
	.incbin "sound/direct_sound_samples/clover/clover_00ae2b88.bin"
	.align 2
DirectSoundWaveData_clover_00aeace4::
	.incbin "sound/direct_sound_samples/clover/clover_00aeace4.bin"
	.align 2
DirectSoundWaveData_clover_00aef9b8::
	.incbin "sound/direct_sound_samples/clover/clover_00aef9b8.bin"
	.align 2
DirectSoundWaveData_clover_00af16b4::
	.incbin "sound/direct_sound_samples/clover/clover_00af16b4.bin"
	.align 2
DirectSoundWaveData_clover_00af3078::
	.incbin "sound/direct_sound_samples/clover/clover_00af3078.bin"
	.align 2
DirectSoundWaveData_clover_00af48bc::
	.incbin "sound/direct_sound_samples/clover/clover_00af48bc.bin"
	.align 2
DirectSoundWaveData_clover_00af5d68::
	.incbin "sound/direct_sound_samples/clover/clover_00af5d68.bin"
	.align 2
DirectSoundWaveData_clover_00af7364::
	.incbin "sound/direct_sound_samples/clover/clover_00af7364.bin"
	.align 2
DirectSoundWaveData_clover_00af8978::
	.incbin "sound/direct_sound_samples/clover/clover_00af8978.bin"
	.align 2
DirectSoundWaveData_clover_00afb634::
	.incbin "sound/direct_sound_samples/clover/clover_00afb634.bin"
	.align 2
DirectSoundWaveData_clover_00b00000::
	.incbin "sound/direct_sound_samples/clover/clover_00b00000.bin"
	.align 2
DirectSoundWaveData_clover_00b026d0::
	.incbin "sound/direct_sound_samples/clover/clover_00b026d0.bin"
	.align 2
DirectSoundWaveData_clover_00b04ccc::
	.incbin "sound/direct_sound_samples/clover/clover_00b04ccc.bin"
	.align 2
DirectSoundWaveData_clover_00b266ac::
	.incbin "sound/direct_sound_samples/clover/clover_00b266ac.bin"
	.align 2
DirectSoundWaveData_clover_00b28fcc::
	.incbin "sound/direct_sound_samples/clover/clover_00b28fcc.bin"
	.align 2
DirectSoundWaveData_clover_00b2ba94::
	.incbin "sound/direct_sound_samples/clover/clover_00b2ba94.bin"
	.align 2
DirectSoundWaveData_clover_00b2e6ec::
	.incbin "sound/direct_sound_samples/clover/clover_00b2e6ec.bin"
	.align 2
DirectSoundWaveData_clover_00b32480::
	.incbin "sound/direct_sound_samples/clover/clover_00b32480.bin"
	.align 2
DirectSoundWaveData_clover_00b34c50::
	.incbin "sound/direct_sound_samples/clover/clover_00b34c50.bin"
	.align 2
DirectSoundWaveData_clover_00b369d0::
	.incbin "sound/direct_sound_samples/clover/clover_00b369d0.bin"
	.align 2
DirectSoundWaveData_clover_00b3749c::
	.incbin "sound/direct_sound_samples/clover/clover_00b3749c.bin"
	.align 2
DirectSoundWaveData_clover_00b399ac::
	.incbin "sound/direct_sound_samples/clover/clover_00b399ac.bin"
	.align 2
DirectSoundWaveData_clover_00b3c1a0::
	.incbin "sound/direct_sound_samples/clover/clover_00b3c1a0.bin"
	.align 2
DirectSoundWaveData_clover_00b3c980::
	.incbin "sound/direct_sound_samples/clover/clover_00b3c980.bin"
	.align 2
DirectSoundWaveData_clover_00b3de70::
	.incbin "sound/direct_sound_samples/clover/clover_00b3de70.bin"
	.align 2
DirectSoundWaveData_clover_00b3f19c::
	.incbin "sound/direct_sound_samples/clover/clover_00b3f19c.bin"
	.align 2
DirectSoundWaveData_clover_00b45db8::
	.incbin "sound/direct_sound_samples/clover/clover_00b45db8.bin"
	.align 2
DirectSoundWaveData_clover_00b47db4::
	.incbin "sound/direct_sound_samples/clover/clover_00b47db4.bin"
	.align 2
DirectSoundWaveData_clover_00b4cf68::
	.incbin "sound/direct_sound_samples/clover/clover_00b4cf68.bin"
	.align 2
DirectSoundWaveData_clover_00b4daf8::
	.incbin "sound/direct_sound_samples/clover/clover_00b4daf8.bin"
	.align 2
DirectSoundWaveData_clover_00b4e664::
	.incbin "sound/direct_sound_samples/clover/clover_00b4e664.bin"
	.align 2
DirectSoundWaveData_clover_00b5cc74::
	.incbin "sound/direct_sound_samples/clover/clover_00b5cc74.bin"
	.align 2
DirectSoundWaveData_clover_00b614c8::
	.incbin "sound/direct_sound_samples/clover/clover_00b614c8.bin"
	.align 2
DirectSoundWaveData_clover_00b64c2c::
	.incbin "sound/direct_sound_samples/clover/clover_00b64c2c.bin"
	.align 2
DirectSoundWaveData_clover_00b66fe4::
	.incbin "sound/direct_sound_samples/clover/clover_00b66fe4.bin"
	.align 2
DirectSoundWaveData_clover_00b6ac24::
	.incbin "sound/direct_sound_samples/clover/clover_00b6ac24.bin"
	.align 2
DirectSoundWaveData_clover_00b76e38::
	.incbin "sound/direct_sound_samples/clover/clover_00b76e38.bin"
	.align 2
DirectSoundWaveData_clover_00b8a8b4::
	.incbin "sound/direct_sound_samples/clover/clover_00b8a8b4.bin"
	.align 2
DirectSoundWaveData_clover_00b8b468::
	.incbin "sound/direct_sound_samples/clover/clover_00b8b468.bin"
	.align 2
DirectSoundWaveData_clover_00b8d390::
	.incbin "sound/direct_sound_samples/clover/clover_00b8d390.bin"
	.align 2
DirectSoundWaveData_clover_00b8dbe0::
	.incbin "sound/direct_sound_samples/clover/clover_00b8dbe0.bin"
	.align 2
DirectSoundWaveData_clover_00b8f3b8::
	.incbin "sound/direct_sound_samples/clover/clover_00b8f3b8.bin"
	.align 2
DirectSoundWaveData_clover_00b928fc::
	.incbin "sound/direct_sound_samples/clover/clover_00b928fc.bin"
	.align 2
DirectSoundWaveData_clover_00b964cc::
	.incbin "sound/direct_sound_samples/clover/clover_00b964cc.bin"
	.align 2
DirectSoundWaveData_clover_00b991f0::
	.incbin "sound/direct_sound_samples/clover/clover_00b991f0.bin"
	.align 2
DirectSoundWaveData_clover_00b9c000::
	.incbin "sound/direct_sound_samples/clover/clover_00b9c000.bin"
	.align 2
DirectSoundWaveData_clover_00c00000::
	.incbin "sound/direct_sound_samples/clover/clover_00c00000.bin"
	.align 2
DirectSoundWaveData_clover_00c02b24::
	.incbin "sound/direct_sound_samples/clover/clover_00c02b24.bin"
	.align 2
DirectSoundWaveData_clover_00c04304::
	.incbin "sound/direct_sound_samples/clover/clover_00c04304.bin"
	.align 2
DirectSoundWaveData_clover_00c054d8::
	.incbin "sound/direct_sound_samples/clover/clover_00c054d8.bin"
	.align 2
DirectSoundWaveData_clover_00c12000::
	.incbin "sound/direct_sound_samples/clover/clover_00c12000.bin"
	.align 2
DirectSoundWaveData_clover_00c1e040::
	.incbin "sound/direct_sound_samples/clover/clover_00c1e040.bin"
	.align 2
DirectSoundWaveData_clover_00c21770::
	.incbin "sound/direct_sound_samples/clover/clover_00c21770.bin"
	.align 2
DirectSoundWaveData_clover_00c26d8c::
	.incbin "sound/direct_sound_samples/clover/clover_00c26d8c.bin"
	.align 2
DirectSoundWaveData_clover_00c29798::
	.incbin "sound/direct_sound_samples/clover/clover_00c29798.bin"
	.align 2
DirectSoundWaveData_clover_00c2bd2c::
	.incbin "sound/direct_sound_samples/clover/clover_00c2bd2c.bin"
	.align 2
DirectSoundWaveData_clover_00c30e18::
	.incbin "sound/direct_sound_samples/clover/clover_00c30e18.bin"
	.align 2
DirectSoundWaveData_clover_00c37268::
	.incbin "sound/direct_sound_samples/clover/clover_00c37268.bin"
	.align 2
DirectSoundWaveData_clover_00c38714::
	.incbin "sound/direct_sound_samples/clover/clover_00c38714.bin"
	.align 2
DirectSoundWaveData_clover_00c3b168::
	.incbin "sound/direct_sound_samples/clover/clover_00c3b168.bin"
	.align 2
DirectSoundWaveData_clover_00c4037c::
	.incbin "sound/direct_sound_samples/clover/clover_00c4037c.bin"
	.align 2
DirectSoundWaveData_clover_00c41260::
	.incbin "sound/direct_sound_samples/clover/clover_00c41260.bin"
	.align 2
DirectSoundWaveData_clover_00c42024::
	.incbin "sound/direct_sound_samples/clover/clover_00c42024.bin"
	.align 2
DirectSoundWaveData_clover_00c446cc::
	.incbin "sound/direct_sound_samples/clover/clover_00c446cc.bin"
	.align 2
DirectSoundWaveData_clover_00c4847c::
	.incbin "sound/direct_sound_samples/clover/clover_00c4847c.bin"
	.align 2
DirectSoundWaveData_clover_00c4cb30::
	.incbin "sound/direct_sound_samples/clover/clover_00c4cb30.bin"
	.align 2
DirectSoundWaveData_clover_00c4ff10::
	.incbin "sound/direct_sound_samples/clover/clover_00c4ff10.bin"
	.align 2
DirectSoundWaveData_clover_00c52080::
	.incbin "sound/direct_sound_samples/clover/clover_00c52080.bin"
	.align 2
DirectSoundWaveData_clover_00c54d60::
	.incbin "sound/direct_sound_samples/clover/clover_00c54d60.bin"
	.align 2
DirectSoundWaveData_clover_00c5be78::
	.incbin "sound/direct_sound_samples/clover/clover_00c5be78.bin"
	.align 2
DirectSoundWaveData_clover_00c5ccb8::
	.incbin "sound/direct_sound_samples/clover/clover_00c5ccb8.bin"
	.align 2
DirectSoundWaveData_clover_00c5eb88::
	.incbin "sound/direct_sound_samples/clover/clover_00c5eb88.bin"
	.align 2
DirectSoundWaveData_clover_00c5f89c::
	.incbin "sound/direct_sound_samples/clover/clover_00c5f89c.bin"
	.align 2
DirectSoundWaveData_clover_00c600f4::
	.incbin "sound/direct_sound_samples/clover/clover_00c600f4.bin"
	.align 2
DirectSoundWaveData_clover_00c60db0::
	.incbin "sound/direct_sound_samples/clover/clover_00c60db0.bin"
	.align 2
DirectSoundWaveData_clover_00c63fcc::
	.incbin "sound/direct_sound_samples/clover/clover_00c63fcc.bin"
	.align 2
DirectSoundWaveData_clover_00c66bd4::
	.incbin "sound/direct_sound_samples/clover/clover_00c66bd4.bin"
	.align 2
DirectSoundWaveData_clover_00c6a3e8::
	.incbin "sound/direct_sound_samples/clover/clover_00c6a3e8.bin"
	.align 2
DirectSoundWaveData_clover_00c70c9c::
	.incbin "sound/direct_sound_samples/clover/clover_00c70c9c.bin"
	.align 2
DirectSoundWaveData_clover_00c7601c::
	.incbin "sound/direct_sound_samples/clover/clover_00c7601c.bin"
	.align 2
DirectSoundWaveData_clover_00c76afc::
	.incbin "sound/direct_sound_samples/clover/clover_00c76afc.bin"
	.align 2
DirectSoundWaveData_clover_00c931b4::
	.incbin "sound/direct_sound_samples/clover/clover_00c931b4.bin"
	.align 2
DirectSoundWaveData_clover_00caf6d4::
	.incbin "sound/direct_sound_samples/clover/clover_00caf6d4.bin"
	.align 2
DirectSoundWaveData_clover_00cc3e90::
	.incbin "sound/direct_sound_samples/clover/clover_00cc3e90.bin"
	.align 2
DirectSoundWaveData_clover_00e26790::
	.incbin "sound/direct_sound_samples/clover/clover_00e26790.bin"
	.align 2
DirectSoundWaveData_clover_00eb0b20::
	.incbin "sound/direct_sound_samples/clover/clover_00eb0b20.bin"
	.align 2
DirectSoundWaveData_clover_00eb65e8::
	.incbin "sound/direct_sound_samples/clover/clover_00eb65e8.bin"
	.align 2
DirectSoundWaveData_clover_00eb8858::
	.incbin "sound/direct_sound_samples/clover/clover_00eb8858.bin"
	.align 2
DirectSoundWaveData_clover_00ebe71c::
	.incbin "sound/direct_sound_samples/clover/clover_00ebe71c.bin"
	.align 2
DirectSoundWaveData_clover_00ee57fc::
	.incbin "sound/direct_sound_samples/clover/clover_00ee57fc.bin"
	.align 2
DirectSoundWaveData_clover_00eefa44::
	.incbin "sound/direct_sound_samples/clover/clover_00eefa44.bin"
	.align 2
DirectSoundWaveData_clover_00ef24c0::
	.incbin "sound/direct_sound_samples/clover/clover_00ef24c0.bin"
	.align 2
DirectSoundWaveData_clover_00ef3370::
	.incbin "sound/direct_sound_samples/clover/clover_00ef3370.bin"
	.align 2
DirectSoundWaveData_clover_00ef89cc::
	.incbin "sound/direct_sound_samples/clover/clover_00ef89cc.bin"
	.align 2
DirectSoundWaveData_clover_00f029d8::
	.incbin "sound/direct_sound_samples/clover/clover_00f029d8.bin"
	.align 2
DirectSoundWaveData_clover_00f1248c::
	.incbin "sound/direct_sound_samples/clover/clover_00f1248c.bin"
	.align 2
DirectSoundWaveData_clover_00f30774::
	.incbin "sound/direct_sound_samples/clover/clover_00f30774.bin"
	.align 2
DirectSoundWaveData_clover_00f31a60::
	.incbin "sound/direct_sound_samples/clover/clover_00f31a60.bin"
	.align 2
DirectSoundWaveData_clover_00f35790::
	.incbin "sound/direct_sound_samples/clover/clover_00f35790.bin"
	.align 2
DirectSoundWaveData_clover_00f3cd1c::
	.incbin "sound/direct_sound_samples/clover/clover_00f3cd1c.bin"
	.align 2
DirectSoundWaveData_clover_00f3d80c::
	.incbin "sound/direct_sound_samples/clover/clover_00f3d80c.bin"
	.align 2
DirectSoundWaveData_clover_00f85870::
	.incbin "sound/direct_sound_samples/clover/clover_00f85870.bin"
	.align 2
DirectSoundWaveData_clover_00fc2068::
	.incbin "sound/direct_sound_samples/clover/clover_00fc2068.bin"
	.align 2
DirectSoundWaveData_clover_00fc65e8::
	.incbin "sound/direct_sound_samples/clover/clover_00fc65e8.bin"
	.align 2
DirectSoundWaveData_clover_00fc8568::
	.incbin "sound/direct_sound_samples/clover/clover_00fc8568.bin"
	.align 2
DirectSoundWaveData_clover_00febda0::
	.incbin "sound/direct_sound_samples/clover/clover_00febda0.bin"
	.align 2
DirectSoundWaveData_clover_00ff00ac::
	.incbin "sound/direct_sound_samples/clover/clover_00ff00ac.bin"
	.align 2
DirectSoundWaveData_clover_00ff3c60::
	.incbin "sound/direct_sound_samples/clover/clover_00ff3c60.bin"
	.align 2
DirectSoundWaveData_clover_00ff66b4::
	.incbin "sound/direct_sound_samples/clover/clover_00ff66b4.bin"
	.align 2
DirectSoundWaveData_clover_00ff9188::
	.incbin "sound/direct_sound_samples/clover/clover_00ff9188.bin"
