	.section .rodata
	.align 2

ProgrammableWaveData_clover_004a31ec::
	.incbin "sound/programmable_wave_samples/clover/clover_004a31ec.pcm"

ProgrammableWaveData_clover_004a320c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a320c.pcm"

ProgrammableWaveData_clover_004a321c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a321c.pcm"

ProgrammableWaveData_clover_004a322c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a322c.pcm"

ProgrammableWaveData_clover_004a323c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a323c.pcm"

ProgrammableWaveData_clover_004a324c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a324c.pcm"

ProgrammableWaveData_clover_004a325c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a325c.pcm"

ProgrammableWaveData_clover_004a327c::
	.incbin "sound/programmable_wave_samples/clover/clover_004a327c.pcm"

ProgrammableWaveData_clover_00850260::
	.incbin "sound/programmable_wave_samples/clover/clover_00850260.pcm"

