IcespireTown_House1_MapScripts::
	.byte 0

IcespireTown_House1_EventScript_SilvansWife::
	lock
	faceplayer
	msgbox IcespireTown_House1_Text_SilvansWife, MSGBOX_DEFAULT
	release
	end

IcespireTown_House1_Text_SilvansWife:
	.string "WOMAN: Oh! Are you the trainer\n"
	.string "who's challenging my husband?\p"
	.string "SILVAN talks about every\n"
	.string "challenger at dinner. He loves\l"
	.string "you all, you know. Every one.\p"
	.string "He's been so HAPPY since the\n"
	.string "DIRECTOR'S people came. Before\l"
	.string "the winter, he had these awful\l"
	.string "headaches. They just stopped.\p"
	.string "I asked one of the researchers\n"
	.string "about it - a polite young man\l"
	.string "in a white coat - and he said,\l"
	.string "'The cold quiets the mind.'\p"
	.string "Isn't that lovely?\p"
	.string "I don't really know what TEAM\n"
	.string "VEIL does. SILVAN says it's\l"
	.string "conservation work.\p"
	.string "I haven't been down to the\n"
	.string "south wall in... I think years\l"
	.string "now. I don't know why I\l"
	.string "stopped going.$"
